### ISSUE TITLE
hi, I can not run demo on Mac

### ISSUE THREAD

**Issue by zhuyiif** [jhanssen/node-uma8#1]
```
Users/yizhu/node-uma8/node_modules/uma8/index.js:15
        internal.open(this._uma8, device);
                 ^

Error: Can't claim interface
    at Uma8.open (/Users/yizhu/node-uma8/node_modules/uma8/index.js:15:18)
    at Object.<anonymous> (/Users/yizhu/node-uma8/app.js:11:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

```

**Comment by jhanssen** [comment]
I believe this means that OS X has already installed a driver for the device, see the following link for some possible solutions: https://github.com/libusb/libusb/wiki/FAQ#How_can_I_run_libusb_applications_under_Mac_OS_X_if_there_is_already_a_kernel_extension_installed_for_the_device
